column_cleanup = {'All': 'alliance',
                  'Area': 'area',
                  'Brexit': 'brexit_party',
                  'Change UK': 'change_uk',
                  'Client': 'client',
                  'Con': 'conservative',
                  'Date(s)Conducted': 'dates',
                  'Date(s)conducted': 'dates',
                  'Datesconducted': 'dates',
                  'Dates conducted': 'dates',
                  'Date(s) conducted': 'dates',
                  'Green': 'green',
                  'Lab': 'labour',
                  'Lead': 'lead',
                  'Lib': 'liberal',
                  'Lib Dem': 'liberal_democrat',
                  'Lib Dems': 'liberal_democrat',
                  'Other': 'others',
                  'Others': 'others',
                  'Plaid Cymru': 'plaid_cymru',
                  'Polling Organisation / Client': 'pollster_client',
                  'Polling organisation/client': 'pollster_client',
                  'Pollster': 'pollster',
                  'Pollster/Client': 'pollster_client',
                  'Pollster/client(s)': 'pollster_client',
                  'Reform': 'reform_uk',
                  'SDP': 'social_democratic_party',
                  'SLD': 'liberal_democrat',
                  'SNP': 'scottish_national_party',
                  'Sample size': 'sample_size',
                  'Samplesize': 'sample_size',
                  'Surveyend date': 'dates',
                  'UKIP': 'united_kingdom_independence_party',
                  'Reclaim Party': 'reclaim_party',
                  'Brexit Party': 'brexit_party',
                  }

pollster_cleanup = {
    'Populus Online': 'Populus',
    'ComRes-': 'Savanta',
    'ComRes': 'Savanta',
    'Savanta ComRes': 'Savanta',
    'SavantaComRes': 'Savanta',
    'Ipsos MOR': 'Ipsos MORI',
    'Ipsos': 'Ipsos MORI',
    'MORI': 'Ipsos MORI',
    'Ipsos-MORI': 'Ipsos MORI',
    'Ipsos Mori': 'Ipsos MORI',
    'Harris': 'Harris Interactive',
    'Harris Interative': 'Harris Interactive',
    'Angus Reid Public Opinion': 'Angus Reid Strategies',
    'TNS BMRB': 'TNS',
    'Focaldata': 'FocalData',
    'ICM': 'ICM Research',
    'Kantar': 'Verian',
    'Kantar Public': 'Verian',
    'BMG': 'BMG Research',
    'Lord Ashcroft': 'Lord Ashcroft Polls',
    'TNS-BMRB': 'TNS',
    'Findoutnow': 'Find Out Now',
    'FindOutNow': 'Find Out Now',
    'Techne': 'Techne UK',
    'Survation (MRP update)': 'Survation',
    'J&L Partners': 'JL Partners Polls',
    'Redfield & Wilton': 'Redfield & Wilton Strategies',
    'People Polling': 'PeoplePolling',
    'More In Common': 'More in Common',
    'Omnisis': 'We Think',
    'Whitestone insight': 'Whitestone Insight',
}
